# Étape de construction
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Étape d'exécution
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .

ENV PORT=3000
ENV MONGO_URI=mongodb://mongo:27017/9hiwa

EXPOSE 3000

CMD ["node", "server.js"]